#!/bin/bash
# optimize_host_network.sh
# Applies the successful MaHarNet 5G fine-tuning to the Host Network Stack

# Configuration
PROFILE_NAME="MaHarNet5G" # We will target the primary one
# Auto-detect default interface or use wlp1s0
DEFAULT_IF=$(ip route show default | awk '/default/ {print $5}' | head -n1)
INTERFACE="${1:-${DEFAULT_IF:-wlp1s0}}"
PASSWORD="#ThawZin2k77!"
REG_DOMAIN="US"
TX_POWER="2000"           # 20dBm
MSS_VALUE="1320"          # MTU (1360) - 40

echo "🚀 Applying MaHarNet 5G Optimizations to Host..."

# 1. Update NetworkManager Profile (Credentials & Power Save)
echo "🔐 Updating NetworkManager Profile ($PROFILE_NAME)..."
# Ensure the profile exists, if not create it (auto-connect=yes)
if nmcli connection show "$PROFILE_NAME" >/dev/null 2>&1; then
    nmcli connection modify "$PROFILE_NAME" \
        wifi-sec.key-mgmt wpa-psk \
        wifi-sec.psk "$PASSWORD" \
        wifi.powersave disable \
        802-11-wireless.cloned-mac-address "44:fa:66:c5:44:a1" \
        ipv4.method auto
else
    echo "⚠️  Profile '$PROFILE_NAME' not found! Please connect once manually or rename existing duplicate."
fi

# 2. Create Dispatcher Script for Dynamic Optimization (Reg/Tx/MSS)
echo "root" | sudo -S echo "🛠️  Installing NetworkManager Dispatcher Script..."
DISPATCHER_PATH="/etc/NetworkManager/dispatcher.d/99-optimize-maharnet"

sudo bash -c "cat > $DISPATCHER_PATH" <<EOF
#!/bin/bash
# Auto-generated by AntiGravity
INTERFACE=\$1
ACTION=\$2

if [ "\$INTERFACE" = "$INTERFACE" ] && [ "\$ACTION" = "up" ]; then
    logger "🚀 AntiGravity: Optimizing \$INTERFACE for MaHarNet 5G..."
    
    # 1. Regulatory Domain (Critical for 5G channels)
    iw reg set $REG_DOMAIN
    
    # 2. TxPower (Critical for Stability)
    iw dev \$INTERFACE set txpower fixed $TX_POWER
    
    # 3. MSS Clamping (Critical for "Stalling")
    # Apply to OUTPUT (Host traffic) and FORWARD (if acting as gateway)
    iptables -t mangle -A OUTPUT -p tcp --tcp-flags SYN,RST SYN -o \$INTERFACE -j TCPMSS --set-mss $MSS_VALUE
    iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o \$INTERFACE -j TCPMSS --set-mss $MSS_VALUE
    
    logger "✅ AntiGravity: Optimizations Applied (Reg=$REG_DOMAIN, Tx=$TX_POWER, MSS=$MSS_VALUE)"
fi
EOF

sudo chmod +x $DISPATCHER_PATH
echo "✅ Dispatcher Installed: $DISPATCHER_PATH"

# 3. Immediate Application (For current session)
echo "⚡ Applying Settings Immediately..."
sudo iw reg set $REG_DOMAIN
sudo iw dev $INTERFACE set txpower fixed $TX_POWER
sudo iptables -t mangle -A OUTPUT -p tcp --tcp-flags SYN,RST SYN -o $INTERFACE -j TCPMSS --set-mss $MSS_VALUE

echo "🎉 Done! Your host adapter is now optimized."
echo "   - Profile: $PROFILE_NAME (Password Updated)"
echo "   - Regulatory: $REG_DOMAIN"
echo "   - TxPower: 20dBm"
echo "   - TCP MSS: $MSS_VALUE (Anti-Stall)"
